package com.admin.view;

import com.admin.controler.DataSubKriteria;
import com.formdev.flatlaf.FlatLightLaf;

public class FormSubKriteria extends javax.swing.JFrame {

      public FormSubKriteria() {
            initComponents();
            DataSubKriteria form = new DataSubKriteria();
            form.KodeSubK(cbb_sub_kriteria);
      }

      /**
       * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jPanel1 = new javax.swing.JPanel();
            cbb_sub_kriteria = new combobox.Combobox();
            txt_keterangan = new textfield.TextField();
            txt_nilai = new textfield.TextField();
            btn_simpan = new swing.ButtonGradient();
            btn_ubah = new swing.ButtonGradient();

            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
            getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jPanel1.setBackground(new java.awt.Color(255, 255, 255));
            jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            cbb_sub_kriteria.setForeground(new java.awt.Color(97, 103, 122));
            cbb_sub_kriteria.setLabeText("Kode Sub Kriteria");
            jPanel1.add(cbb_sub_kriteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 260, -1));

            txt_keterangan.setBackground(new java.awt.Color(255, 255, 255));
            txt_keterangan.setForeground(new java.awt.Color(97, 103, 122));
            txt_keterangan.setLabelText("Keterangan");
            jPanel1.add(txt_keterangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 260, -1));

            txt_nilai.setBackground(new java.awt.Color(255, 255, 255));
            txt_nilai.setForeground(new java.awt.Color(97, 103, 122));
            txt_nilai.setLabelText("Nilai");
            jPanel1.add(txt_nilai, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 260, -1));

            btn_simpan.setText("Simpan");
            btn_simpan.setColor1(new java.awt.Color(35, 20, 226));
            btn_simpan.setColor2(new java.awt.Color(209, 18, 235));
            btn_simpan.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btn_simpanActionPerformed(evt);
                  }
            });
            jPanel1.add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 130, 30));

            btn_ubah.setText("Ubah");
            btn_ubah.setColor1(new java.awt.Color(35, 20, 226));
            btn_ubah.setColor2(new java.awt.Color(209, 18, 235));
            btn_ubah.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btn_ubahActionPerformed(evt);
                  }
            });
            jPanel1.add(btn_ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 130, 30));

            getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 500));

            pack();
            setLocationRelativeTo(null);
      }// </editor-fold>//GEN-END:initComponents

      private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
            DataSubKriteria method = new DataSubKriteria();
            method.TambahData(cbb_sub_kriteria, txt_keterangan, txt_nilai);            
      }//GEN-LAST:event_btn_simpanActionPerformed

      private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
           
      }//GEN-LAST:event_btn_ubahActionPerformed

      /**
       * @param args the command line arguments
       */
      public static void main(String args[]) {
            FlatLightLaf.setup();
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                  public void run() {
                        new FormSubKriteria().setVisible(true);
                  }
            });
      }

      // Variables declaration - do not modify//GEN-BEGIN:variables
      private swing.ButtonGradient btn_simpan;
      private swing.ButtonGradient btn_ubah;
      private combobox.Combobox cbb_sub_kriteria;
      private javax.swing.JPanel jPanel1;
      private textfield.TextField txt_keterangan;
      private textfield.TextField txt_nilai;
      // End of variables declaration//GEN-END:variables
}
